/** Organizations / clients / bodies — single source for Cred strip + footer. */
export const TRUSTED_ORGS = [
  'Rivian',
  'Samsung',
  'Goodyear',
  'LTIMindtree',
  'HCL Technologies',
  'IBM',
  'Singtel Optus',
  'Wipro',
  'Infosys',
  'TCS (Tata Consultancy Services)',
  'Accenture',
  'Microsoft',
  'Ionis Pharmaceuticals',
  'IEEE',
  'IET',
  'AAA',
  'IAI',
  'Constellation Research',
  'SAINexus',
  'ExxonMobil Chemical (USA)',
  'Tesla',
  'Amazon',
  'MGA Entertainment',
  'Viacom',
  'HBO',
  'Singapore Stock Exchange',
  'Citi Bank',
  'Warner Bros.',
  'Tyco International',
  'Merck',
  'Commonwealth Bank of Australia',
  'Fonterra (New Zealand)',
  'IAEA',
] as const
